### ISSUE TITLE
https://bibdata.princeton.edu/events Gives a 502

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/marc_liberation#1067] opened 2021-02-10 18:31 UTC
We should paginate this so we can look at the page... https://bibdata.princeton.edu/events

**Comment by christinach** [comment] 2021-02-10 18:32
Until we do this you can see the events through https://bibdata.princeton.edu/events.json

**Comment by christinach** [comment] 2021-02-10 18:37
closing as duplicate of https://github.com/pulibrary/marc_liberation/issues/690
there is also some more information in the older ticket regarding the pagination.

**Closed by christinach** 2021-02-10 18:37 UTC
