### ISSUE TITLE
[Bibdata/production] OCIError: ORA-01722: invalid number

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/marc_liberation#437] opened 2018-08-15 14:21 UTC
## Backtrace

    line 14 of [PROJECT_ROOT]/app/controllers/availability_controller.rb: index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/35827692)

**Comment by eliotjordan** [comment] 2018-08-28 15:44
This is still an issue.

**Comment by escowles** [comment] 2018-09-14 18:32
Dupe of #449

**Closed by escowles** 2018-09-14 18:32 UTC
Labels: Priority, bug
