### ISSUE TITLE
Index bound-with materials

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#800] opened 2020-09-22 17:21 UTC
refs #922

**Comment by mzelesky** [comment] 2020-09-22 17:48
There are 2 different data models we have to account for. The first model is data that is migrated from Voyager to Alma. See https://knowledge.exlibrisgroup.com/Alma/Implementation_and_Migration/Migration_Guides_and_Tutorials/Voyager_to_Alma_Migration_Guide#Boundwiths for this information.

The second model is post-migration. Emory University posted a good tutorial on this. https://emory.screenstepslive.com/s/alma/m/cat/l/653607-bound-withs-items-with-multiple-works-bound-together

Essentially, a bound-with item is only associated with one bib record. In the case of migrated records, a new record is created with the title 'Host bibliographic record for boundwith item [barcode]'. It then has one 774 field added for each bibliographic record the item is attached to. There is no linkage back to this record in the associated bib records.

In the case of records created natively in Alma, a bound-with item is only linked to one of the attached bib records. That record has a 774 field for each additional bib record attached. The linked records have a 773 field that links back to the host bib. That is the only connection between the records.

**Comment by hackartisan** [comment] 2021-01-26 19:35
closed as duplicate of #922; availability-related considerations will be part of #654

**Closed** 2021-01-26 19:35 UTC
Labels: alma-implementation
